"use client"

import { useMemo, useState } from "react"
import { motion } from "framer-motion"
import { ChevronDown, Github } from "lucide-react"
import { projects } from "@/lib/site-data"

export function ProjectsSection() {
  const [filter, setFilter] = useState("All")
  const [expanded, setExpanded] = useState<string | null>(null)
  const filters = ["All", "Full-stack", "Data analysis"]
  const visible = useMemo(() => projects.filter((project) => filter === "All" || (filter === "Data analysis" ? project.title.startsWith("IPL") : !project.title.startsWith("IPL"))), [filter])
  return <section id="projects" className="section-shell"><div className="flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="section-heading"><p className="eyebrow">Selected work</p><h2>Projects with a practical point of view.</h2></div><div className="flex flex-wrap gap-2" aria-label="Filter projects">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "filter-button active" : "filter-button"}>{item}</button>)}</div></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{visible.map((project, index) => { const isOpen = expanded === project.title; return <motion.article key={project.title} className="surface-card flex flex-col p-6" initial={{ opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ delay: index * .07 }} whileHover={{ y: -5 }}><div className="flex items-start justify-between gap-4"><p className="eyebrow">{project.date}</p><span className="project-index">0{index + 1}</span></div><h3 className="mt-5 text-2xl font-semibold tracking-tight">{project.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{project.description}</p><div className="mt-5 flex flex-wrap gap-2">{project.tech.map((item) => <span className="tech-badge" key={item}>{item}</span>)}</div><div className="mt-6 flex items-center gap-3 border-t border-border pt-5"><a className="button-primary flex-1 justify-center" href={project.githubLink} target="_blank" rel="noreferrer"><Github data-icon="inline-start" /> View on GitHub</a><button className="icon-button" onClick={() => setExpanded(isOpen ? null : project.title)} aria-expanded={isOpen} aria-label={`${isOpen ? "Collapse" : "Expand"} ${project.title} details`}><ChevronDown className={isOpen ? "rotate-180 transition-transform" : "transition-transform"} /></button></div>{isOpen && <div className="mt-5 border-t border-border pt-5"><p className="eyebrow mb-3">Key highlights</p><ul className="grid gap-3 text-sm leading-6 text-muted-foreground">{project.highlights.map((highlight) => <li key={highlight} className="flex gap-3"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary" aria-hidden="true" />{highlight}</li>)}</ul></div>}</motion.article> })}</div></section>
}
